---
# updated version of Demo4.2.2_Java_NodeJS_CI2.yml / GitHubActions_Demo4.2_NodeJS 
# Demo_5 is for uisng needs keyword, taking backup of test Report + Build files artifact after running tests
name: needs keyword - nodeJS application
on: workflow_dispatch
# on: 
#  push:
#   branches: master
jobs: 
  job_test:
    runs-on: ubuntu-latest 
    steps: 
      - name: Clone the Repo 
        uses: actions/checkout@v5 
      - name: Install nodejs
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci 
      - name: Run tests 
        run: npm test
      - name: Test reports to github repo 
        uses: actions/upload-artifact@v4
        with: 
         name: Test Report
         path: /home/runner/work/GitHubActions_Demo5_NodeJS_Needs_Keyword/GitHubActions_Demo5_NodeJS_Needs_Keyword/test.json
  jobs_build:
    needs: job_test 
    runs-on: ubuntu-latest 
    steps:
      - name: Clone the Repo 
        uses: actions/checkout@v5
      - name: Install nodejs
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build code 
        run: npm run build
      - name: Build Files to github repo 
        uses: actions/upload-artifact@v4
        with: 
         name: Build files
         path: |
          dist/assets/logo.76a8d26b.png 
          dist/index.html
          dist/assets/index.34ed278d.css
          dist/assets/index.d590f20c.js
